shamefullyHoist: true

catalog:
  "@antfu/eslint-config": ^4.17.0
  "@stylistic/stylelint-plugin": ^3.1.3
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.0
  eslint: ^9.31.0
  known-css-properties: ^0.37.0
  stylelint: ^16.22.0
  stylelint-config-html: ^1.1.0
  stylelint-config-standard-scss: ^15.0.1
  stylelint-order: ^7.0.0
  tsdown: ^0.12.9
  vitest: ^3.2.4

onlyBuiltDependencies:
  - rolldown
  - unrs-resolver
