shamefullyHoist: true

catalog:
  "@antfu/eslint-config": ^4.14.1
  "@stylistic/stylelint-plugin": ^3.1.2
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.1
  eslint: ^9.29.0
  known-css-properties: ^0.37.0
  stylelint: ^16.20.0
  stylelint-config-html: ^1.1.0
  stylelint-config-standard-scss: ^15.0.1
  stylelint-order: ^7.0.0
  tsdown: ^0.12.7
  vitest: ^3.2.3

onlyBuiltDependencies:
  - esbuild
  - rolldown
  - unrs-resolver
